single:
  python_version: 3.8
  clustering: single # parallel, ray, etc.
  environment_params:
    WORLD_SIZE: 2
    DISTRIBUTED_ARGS: "--nproc_per_node 2 --nnodes 1 --node_rank 0 --master_addr localhost --master_port 6000"
    TASK: "LAMBADA"
    VALID_DATA: <lambada path>
    VOCAB_FILE: gpt2-vocab.json
    MERGE_FILE: gpt2-merges.txt
    CHECKPOINT: checkpoints/gpt2_345m
  requirements: ./requirements.txt
  main: python -m torch.distributed.launch $DISTRIBUTED_ARGS ./tasks/main.py \
               --task $TASK \
               --valid-data $VALID_DATA \
               --tokenizer-type GPT2BPETokenizer \
               --strict-lambada \
               --vocab-file $VOCAB_FILE \
               --merge-file $MERGE_FILE \
               --load $CHECKPOINT \
               --tensor-model-parallel-size 1 \
               --num-layers 24 \
               --hidden-size 1024 \
               --num-attention-heads 16 \
               --batch-size 8 \
               --activations-checkpoint-method uniform \
               --seq-length 1024 \
               --max-position-embeddings 1024 \
               --log-interval 10 \
               --fp16 \
               --no-load-optim \
               --no-load-rng
distributed:
  python_version: 3.8
  clustering: parallel
  nodes: 2
  environment_params:
    MASTER_ADDR: localhost
    NODE_RANK: 0
    GPUS_PER_NODE: 2
    NNODES: 1
    DATA_PATH: <Specify path and file prefix>_text_document
    CHECKPOINT_PATH: "./outputs/checkpoint"
    WORLD_SIZE: 2 #$(($GPUS_PER_NODE*$NNODES))
  requirements: ./requirements.txt
  main: python -m torch.distributed.launch --nproc_per_node $GPUS_PER_NODE --nnodes $NNODES --node_rank $NODE_RANK --master_addr $MASTER_ADDR --master_port $MASTER_PORT \
       pretrain_gpt.py \
       --num-layers 24 \
       --hidden-size 1024 \
       --num-attention-heads 16 \
       --micro-batch-size 8 \
       --global-batch-size 64 \
       --seq-length 1024 \
       --max-position-embeddings 1024 \
       --train-iters 500000 \
       --lr-decay-iters 320000 \
       --save $CHECKPOINT_PATH \
       --load $CHECKPOINT_PATH \
       --data-path $DATA_PATH \
       --vocab-file gpt2-vocab.json \
       --merge-file gpt2-merges.txt \
       --data-impl mmap \
       --split 949,50,1 \
       --distributed-backend nccl \
       --lr 0.00015 \
       --lr-decay-style cosine \
       --min-lr 1.0e-5 \
       --weight-decay 1e-2 \
       --clip-grad 1.0 \
       --lr-warmup-fraction .01 \
       --activations-checkpoint-method uniform \
       --log-interval 100 \
       --save-interval 10000 \
       --eval-interval 1000 \
       --eval-iters 10 \
       --fp16
